<?php

namespace AppBundle\Repository;

/**
 * FigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigRepository extends \Doctrine\ORM\EntityRepository
{
}
